## KHobbits - https://github.com/khobbits/ESPHome_Snippets ##
# This file uses deepsleep to awake once a minute to publish sensor data

defaults:
  run_duration: 8s
  sleep_duration: 52s
  wakeup_pin: A4
  ha_entity_id: input_boolean.prevent_deep_sleep

esphome:
  on_boot:
    - priority: 600
      then:
      - deep_sleep.prevent: deepsleep

deep_sleep:
  id: deepsleep
  run_duration: 
    default: ${run_duration}
  sleep_duration: ${sleep_duration}
  wakeup_pin: 
    number: ${wakeup_pin}
    allow_other_uses: true
    inverted: false
    mode:
      input: true
      pullup: true
  wakeup_pin_mode: KEEP_AWAKE

binary_sensor:
  - platform: homeassistant
    entity_id: ${ha_entity_id}
    id: disable_sleep
    publish_initial_state: true
    on_state:
      then:
        if:
          condition:
            lambda: return x;
          then:
            - logger.log: "Preventing deep sleep"
            - deep_sleep.prevent: deepsleep
          else:
            - logger.log: "Allowing deep sleep"
            - deep_sleep.allow: deepsleep
  - platform: gpio
    id: deep_sleep_toggle
    pin: 
      number: ${wakeup_pin}
      allow_other_uses: true